name: manifests-generator
run-name: Generate manifests
on:
  #schedule:
     #- cron: '30 5 * * *'
  workflow_dispatch:
jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GH_TOKEN}}
      - name: Download Syft
        run: |
              curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Start process
        run: |
             python3 manifest_generator.py --f tools.yaml
      - name: Commit changes 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add results/
          git commit -m "Updated manifests"
          git push